### ISSUE TITLE
Should we have the title with the logo?

### ISSUE THREAD

**Issue by ajdaniel** [fit52/ui#19]
Should we have the title of the site in the header, even though the logo is there?

![image](https://user-images.githubusercontent.com/867941/51848384-678ba080-2315-11e9-877b-6be570e6feef.png)

@markvardy how do you feel about it? It might be neater without the text

**Comment by markvardy** [comment]
Yeah, I don't think we lose anything if the text isn't there.

Maybe if we extend the fit52 franchise to other locations we'll have to reconsider 😜
