### ISSUE TITLE
Complete list of participants

### ISSUE THREAD

**Issue by markvardy** [fit52/ui#22]
Create a complete list of participants (like the [current "people" page](http://ibm.biz/hursley-fit52-people)), with the following structure:

Full name | 2k | 5k | Total | 2k PB | 5k PB | #PBs | Best AG |
-- | -- | -- | -- | -- | -- | -- | -- |
Joe Bloggs | 4 | 6 | 0 | 10:14 | 26:45  | 3 | 50.61%

**Comment by ajdaniel** [comment]
Initial page of runners has been published https://fit52.eu-gb.mybluemix.net/runners (adbc5dfd1515e0443e061903eeeae3fc9a5205de) but I need to add more details for each runner

**Comment by ajdaniel** [comment]
This is completed with 647fb6992e44da3572052c333d0358fac09e55e5
