### ISSUE TITLE
Separate event results by distance

### ISSUE THREAD

**Issue by davidcurrie** [fit52/ui#25]
Split 2k and 5k participants into two separate results lists or provide a means to filter the results on distance. In particular, the current approach of listing the position across both distances doesn't make a whole lot of sense.

**Comment by ajdaniel** [comment]
This can be easily done with either two tables OR a button to flip between 2k, 5k, or all.

@markvardy would you be happy with me implementing in this way?

**Comment by markvardy** [comment]
I think 2 tables, since there are, effectively, 2 events being carried out at the same time.

@ajdaniel does this need an underlying data change?

**Comment by davidcurrie** [comment]
Looks good - thanks @ajdaniel

**Comment by ajdaniel** [comment]
@markvardy I can do some processing to do this, but only if you think it's okay to alter the positions accordingly.

Also I wonder if it's worth maybe allowing a view of one table with everyone alongside the split table (maybe under tabs)

**Comment by markvardy** [comment]
The more I think about it, the more I'm not sure what having a combined table achieves tbh! So I think the separate tables as you've done it is good.

The question about a data change was to preserve the principle of what we've done so far, which is to do as much of the processing when we load the results rather than when displaying the page.

wrt to position numbers, I think it would make more sense to have the numbers within each table start at 1.

**Comment by ajdaniel** [comment]
What I can do for now is manipulate the data on the front end to show the correct positions.

Sounds like we should raise an issue on the ingestion side to do some separation.

I still believe we should have a 2k course and a 5k course, and an event runs over multiple courses and the UI can just show the results for each course.

**Comment by markvardy** [comment]
Yes, agreed about the separate 2k/5k courses: see fit52/results#16, which I have slightly re-purposed for this.

**Comment by markvardy** [comment]
Also just noticed that although the position numbers are separate now for the event details, the individual's page (e.g. [Bracken](https://fit52.eu-gb.mybluemix.net/runners/131f34a1-84ed-4fe1-b8e1-b63831e77a69)) shows the absolute result. The above issue will fix this also.

**Comment by ajdaniel** [comment]
Very good point, I won't be able to do that on the UI without some serious computation that should happen in the pre-processing
