### ISSUE TITLE
Columns on events are all labelled "Runner"

### ISSUE THREAD

**Issue by markvardy** [fit52/ui#37]
**Describe the bug**
Columns on events are all labelled "Runner"

**To Reproduce**
1. Go to an event, e.g. [event 32](https://fit52.eu-gb.mybluemix.net/events/32)
2. Observe that all columns have the header "Runners"
3. er ...
4. That's it

**Expected behavior**
The columns should have the headers (in order):
* Position
* Name
* Number of times run
* Event time
* Age grading

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version75

(also confirmed on Firefox)

**Comment by ajdaniel** [comment]
Thanks for raising this. It's an obvious bug I missed when converting to React hooks. Completed it now!

**Comment by markvardy** [comment]
Not seeing this fixed on the web site for some reason!

**Comment by ajdaniel** [comment]
ugh, you're right 🤔 will take another look. I swear I am a UI developer, honest

**Comment by ajdaniel** [comment]
Ah, the code works, but the deploy failed and I wasn't notified. Taking a look now

**Comment by ajdaniel** [comment]
This is definitely complete now 👍

**Comment by markvardy** [comment]
I can confirm that! 😸
