### ISSUE TITLE
fit52 web site: 404 'route does not exist'

### ISSUE THREAD

**Issue by markvardy** [fit52/ui#40]
**Describe the bug**
When accessing the [fit52 web site](https://fit52.eu-gb.mybluemix.net/) we get a 404

**To Reproduce**
1. Open an incognito window in a browser (to avoid cached artifacts)
2. Go to https://fit52.eu-gb.mybluemix.net/
3. Get message: `404 Not Found: Requested route ('fit52.eu-gb.mybluemix.net') does not exist.`

**Expected behavior**
The web site displays!

**Screenshots**
n/a

**Desktop (please complete the following information):**
Seen across multiple OS & browsers

**Additional context**
I'm not sure I've looked at this since last year - maybe something has expired?

@ajdaniel I had been intended to get a little more info from you about the web site, in order to be able to troubleshoot issues - we should do that soon ;-)

**Comment by ajdaniel** [comment]
I think this is related to the recent security updates, it looks like the build and deploy [failed](https://travis-ci.org/fit52/ui/builds/631839778).

Looking into it.

**Comment by ajdaniel** [comment]
This should be working now, please can you confirm @markvardy ?

**Comment by markvardy** [comment]
Yes, it's working. Thanks for the prompt action @ajdaniel !

🏆
